steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chatbot', '.']

  # Tag the image for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'gcr.io/$PROJECT_ID/chatbot:latest'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/group4-repo/chatbot:latest'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/group4-repo/chatbot:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatbot'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/group4-repo/chatbot:latest' # Use the Artifact Registry path here
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8008'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/group4-repo/chatbot:latest' # Update the image name here

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY